### ISSUE TITLE
Version Debug no compila

### ISSUE THREAD

**Issue by MacGiv** [Stevendotcom/WelcomeToHell#5]

**Comment by Stevendotcom** [comment]
El error es "Resource not available"? si es asi, el error es esperado, pues no se inicia el audio device. Si conectas auriculares deberia funcionar.

**Comment by Stevendotcom** [comment]
Still, a better way of handling this should be added

**Comment by Stevendotcom** [comment]
The user sent me this
![IMG-20241025-WA0003.jpg](https://github.com/user-attachments/assets/085a2496-a2f5-4289-b9ad-0a209327561a)
