### ISSUE TITLE
Reposicionamiento de balas

### ISSUE THREAD

**Issue by MacGiv** [Stevendotcom/WelcomeToHell#8]
Nota de jugabilidad. Al disparar muchas balas, la pantalla se vuelve un "Bullet-Hell" de balas provenientes del jugador, lo que hace que los enemigos sean destruidos inmediatamente despues de aparecer. Esto genera que llegado a un punto, el jugador no tiene que disparar porque ya es suficiente con las balas que ya fueron disparadas.

![image](https://github.com/user-attachments/assets/a75e9e79-5c09-4fb2-a075-2b33c8243743)

**Comment by Stevendotcom** [comment]
Add limit of bullet
